### PR TITLE
GPIO16 support.

### PR DESCRIPTION
**Pull request by ourairquality**
Need this to blink the LED on nodemcu boards! Was discussed here https://github.com/SuperHouse/esp-open-rtos/issues/60 Have not integrated this with the other gpio functions to avoid a performance regression, and if desired then perhaps that could be a separate PR.

### CODE REVIEW

**Comment by ourairquality** [comment]
Perhaps performance would not be impacted if the gpio number is a constant, because the comparison and dead code would be optimized away. Happy to just bundle this in the gpio_read and gpio_write is that is what people want?

**Comment by resetnow** [comment]
For static inline functions (read/write) yes, branching should be eliminated as a part of constant propagation. And gpio_enable is unlikely to be called very often so I think performance impact will be minimal.

**Comment by foogod** [comment]
Yeah, I think including it as a conditional in the standard `gpio_read`/`gpio_write` would be fine, actually..  If someone's concerned about speed there they should already be using a compile-time constant for pin number (as it optimizes out a lot of the other internals of those functions anyway) and so this would be just another compile-time optimization, so that should be fine..

(Alternately, I'm fine with merging this in as-is for now too if you don't want to make that change for some reason.. just let me know)

**Comment by ourairquality** [comment]
Thank you for the feedback. Actually the i2c driver might be an example that is compromised by poor performance in these paths and uses a dynamic pin configuration, and it also uses the `gpio_enable` function to toggle pins high an low rather than using open drain. There is already an open PR to write a separate 'fast' i2c driver.

I was even thinking of abstracting the i2c driver to support multiple i2c buses so wanted to keep the dynamic pin definitions. The gpio16 pin seems to be in a different class, so perhaps it's fine with separate api functions.

So have split out `gpio16_enable` too for now. Perhaps we need to add inline api functions to switch between input and output on a pin quickly too, without all the configuration too.

**Comment by foogod** [comment]
Hmm, actually now that you mention it, things like the i2c driver also seem to be a good argument for including GPIO16 into the main routines if we can manage it.  It would be really nice if somebody could, for example, do I2C over GPIO16 by just passing "16" to the i2c driver, which they can't do if we keep things separate..

I haven't actually looked at the i2c driver in a while, but if it's using `gpio_enable` to switch modes instead of open-drain then that's probably something we should fix in the i2c driver (and shouldn't be using that bad design as a reason for design decisions elsewhere in the code)..

Having an extra conditional in these routines probably isn't the end of the world either, even if the value isn't a compile-time constant, using things like `__builtin_expect` we should be able to ensure that the GPIO0-15 code remains the fast-path and it will only introduce an extra 2 opcodes (25ns at 80MHz) into that path.  For something like the i2c driver I really doubt that will make any difference to anyone (and if it does we can probably more than make up for it with improvements in the i2c driver (like not using `gpio_enable` to switch modes) instead)..

**Comment by ourairquality** [comment]
@foogod Ok, thanks. Changed the PR to bundle the gpio16 support into the existing api functions. Looking at the I2C driver I also don't think the overhead is significant, and it has delays after changes anyway. Fir the I2C driver, changing the pin from input to output rather than using open drain was a feature, there was a discussion somewhere on the merits of the approach.

**Comment by resetnow** [comment]
Speaking about performance, I have seen mentions of rather slow MMIO register access — people say it takes about <a href="http://www.esp8266.com/viewtopic.php?f=156&t=11275">17 cycles to write a peripheral register</a>. Pure speculation here, but I think cycles could be lost in the glue logic between lx106 memory interface and peripheral bus, which probably doesn't have pipeline support implemented. So these extra branch delays are quite small compared to IO access time.

**Comment by projectgus** [comment]
This looks good to me, thanks @ourairquality . +1 to merge here if noone has any other concerns.

@resetnow , probably the most relevant thing about the ESP8266 CPU is that it has the xtensa "write buffer" feature, with buffer size one. So there can always be one peripheral write "in flight" at a given time without blocking the CPU, as long as it doesn't issue another write that blocks behind it (or a MEMW instruction). This means that some additional conditional tests like the one mentioned may not cause any performance overhead, even if they're not known at compile time, because in a tight loop the conditional can be evaluated during the window when the write buffer is still flushing. I wouldn't guarantee this without measuring it, but that's my suspicion!

**Pull request merged**
