### PR TITLE
sysparam editor: add an echo command.

### PR DESCRIPTION
**Pull request by ourairquality**
Helpful to be able to disable echo when sending commands fast, so that the editor can consume them faster than they arrive. This adds and 'echo' command to toggle echo on and off.

### CODE REVIEW

**Comment by yesco** [comment]
Hi

I would suggest that it doesn't toggle as the state may not be known.
Better to provide on off methods for predictable behavior.

One issue with the Hayes commands for esp8266 is that it's difficult to
assert a state or make sure something starts in the state you want to have,
when using it programmatically.

Anyway just an idea,

cheers

**Comment by ourairquality** [comment]
@yesco Sounds like a good idea thanks. Do you have a suggestion: `echo-on` `echo-off` or `echo 0` `echo 1` etc?

**Comment by ourairquality** [comment]
@yesco Changed to `echo-on` and `echo-off` fwiw.

**Comment by sheinz** [comment]
This looks good to me. I've tried the example. Works great.

**Comment by kanflo** [comment]
Thanks @ourairquality. Just out of curiosity, are you testing sysparam for speed since you need to turn off echoing?

**Comment by ourairquality** [comment]
@kanflo Not looking at performance. My application loads parameters into RAM at startup, and writes very infrequently, performance is not an issue for me, just needed it lightweight and safe. The echo was a problem using the editor to quickly get some automation running because the delay caused the uart input buffer to overflow.

**Comment by yesco** [comment]
Good. Cheers

**Pull request merged**
