### PR TITLE
Add more *_regs.h definitions

### PR DESCRIPTION
**Pull request by foogod**
(Re: issue #8)

Fleshing out a bunch more of the register headers:  Added *_regs.h files for UART, SPI, and RTC memory regions.  Also adding a bunch more register info to dport_regs.h based on info from http://esp8266-re.foogod.com/wiki/Memory_Map#dport0

### CODE REVIEW

**Comment by projectgus** [comment]
This is great, thanks. Are you still working through the register blocks? I can do some if that suits, but I don't want to double up efforts.

**Comment by kanflo** [comment]
Great! I have made use of this in the serial driver.

**Comment by foogod** [comment]
@kanflo: be aware before you pull too much hair out, I just realized the UART(i) macro in this is completely wrong and will result in reading/writing to the wrong memory locations.. Will be submitting a fix as soon as I can get somewhere with full internet access..

**Comment by kanflo** [comment]
@foogod: really? It works well in this commit: https://github.com/kanflo/esp-open-rtos/commit/4473eb7dbdd3dca0d31e67879cc8361522e9e25a. That is of course unless I edited source code in one directory and compiled in another :)

**Comment by foogod** [comment]
Well, if it did work then I have no idea what's going on.. the current definition maps UART(0) to the SPI(0) region, and UART(1) to somewhere outside of the MMIO region entirely (0x5ffff3xx)..  Stupid cut-and-paste error on my part (sorry about that)..

PR #33 should fix it..

**Comment by kanflo** [comment]
Now you have me really worried about what I was up to last night as it clearly should not have worked per your description.

**Pull request merged**
