### PR TITLE
FreeRTOS: Drop reference to xthal_set_intset

### PR DESCRIPTION
**Pull request by resetnow**

### CODE REVIEW

**Comment by kanflo** [comment]
Hi @resetnow. Could you please elaborate on the need for removing xthal_set_intset?

**Comment by resetnow** [comment]
Hi @kanflo — I saw it being discussed <a href="https://github.com/SuperHouse/esp-open-rtos/issues/66">here</a>, and since xthal_set_intset is just one instruction, I thought that eliminating a library dependency could be good for a code size.

**Comment by kanflo** [comment]
Thanks for the pointer @resetnow. Do you have any input @foogod as you where part of the original discussion?

**Comment by projectgus** [comment]
This looks good, it'd be nice not to have to link libhal (some toolchains don't ship it.)

We have a convenience macro for using WSR from C here: core/include/xtensa_ops.h - is it possible to use this? (I noticed you used register contraint 'a' not 'r' in the PR, but I'm not sure if this makes any difference to the output on xtensa.)

**Comment by jcmvbkbc** [comment]
> I noticed you used register contraint 'a' not 'r' in the PR, but I'm not sure if this makes any difference to the output on xtensa

There's no difference in call0 ABI. In windowed ABI 'a' constraint is 'all registers except the stack pointer'.

**Comment by resetnow** [comment]
I have updated the code to use the macro from xtensa_ops.h

**Pull request merged**
