### PR TITLE
SSD1306 OLED Display driver refactored

### PR DESCRIPTION
**Pull request by UncleRus**
Support for SPI connection and different display sizes added, functions documented, example refactored.

@urx Please review.

### CODE REVIEW

**Comment by sheinz** [comment]
still waiting for my display module to arrive so I can try the driver :)

**Comment by UncleRus** [comment]
My arrived in 10 days :) bought it here: https://www.aliexpress.com/item/1pcs-0-96-White-OLED-module-0-96-OLED-New-128X64-OLED-LCD-LED-Display-Module/32595230501.html
And the best part of this module is configurable connection: you can select I2C, 8 or 9 bit SPI.

**Comment by Zaltora** [comment]
Hi @UncleRus ,  Verify if it is a SH1106 or a SSD1306. I don't know if the lib is compatible with both. I had modify my lib from : 

```
_command(0x21); // SSD1306_COLUMNADDR
_command(0);    // column start
_command(127);  // column end
_command(0x22); // SSD1306_PAGEADDR
_command(0);    // page start
_command(7);    // page end (8 pages for 64 rows OLED)
for (k = 0; k < 1024; k++)
{
	for (j = 0; j < 16; ++j)
	{
	spi_tx8(HSPI,ctx->buffer[k]);
		++k;
	}
	--k;
}
```

to:

```
#define M_COL 2
for (i = 0 ; i < 8 ; i++) {
	_command(M_COL & 0xf);
	_command(0x10 | (M_COL >> 4));
	_command(0xB0 | (i & 0x0F));
	for (k = 0; k < 132; k++)
	{
		spi_tx8(HSPI,ctx->buffer[i*132+k]);
	}
}
```

for my screen.
I will test the lib when i will got time with my SH1106.

**Comment by UncleRus** [comment]
@Zaltora, It would be great if you add compatibilty with SH1106! Unfortunately I have only SSD1306 and can't do this. Or you can wait while I buy SH1106, it will took about three weeks.

**Comment by Zaltora** [comment]
I had work to add some additional features with SPI.  I will pull these functions fast as beta, it will allow SPI3 protocol. I will do some test on SH1106 when i will get time, probably next week but not sure :( .
One suggest, add I2C addr to allow 0x3C and 0x3D selection.
```
typedef struct
{
    ssd1306_protocol_t protocol;
#if (SSD1306_I2C_SUPPORT)
    uint8_t dev_addr;               //!< I2C address, used by SSD1306_PROTO_I2C
#endif
    uint8_t cs_pin;               //!< Chip Select GPIO pin, used by SSD1306_PROTO_SPI3, SSD1306_PROTO_SPI4
    uint8_t dc_pin;               //!< Data/Command GPIO pin, used by SSD1306_PROTO_SPI4
    uint8_t width;                //!< Screen width, currently only 128px supported
    uint8_t height;               //!< Screen height, currently supported 16px, 32px, 64px
} ssd1306_t;
```

**Comment by sheinz** [comment]
I've just received my display module, will definitely try this driver out.

**Pull request merged**
