### PR TITLE
Add websocket example

### PR DESCRIPTION
**Pull request by luisbebop**
This is a small websocket client running on top of TLS 1.2 and supporting permessage-deflate extension.

### CODE REVIEW

**Comment by projectgus** [comment]
This looks really really neat functionality, thanks @luisbebop for contributing it! Sorry for the extended silence, I've been away on holidays and I think everyone else has been busy too.

Generally at a glance this looks great. I have a few minor comments:

* As this includes on the sysparam functionality that @foogod wrote, I'd prefer to merge it after the sysparam stuff - and we might put sysparam through in a separate PR to make it easier to track what happened when. Seems like the sysparam stuff is close to being ready to merge, though.

* The separate websocket functionality and the various bits of zlib-functionality might be good things to put into two separate "components" in extras/, so they're easier for people to reuse. What do you think?

* Some of the original source files are missing Copyright/LICENSE notices. If you don't mind, our preferred licensing configuration is public domain/CC0 for examples and "Copyright (C) 2015 xxx. Licensed under the new BSD License as described in the file LICENSE" for other functionality.

Thanks again and sorry for the delayed reply.

**Comment by kanflo** [comment]
Great add on @luisbebop. Regarding the sysparam I think it's ripe for a PR.

**Comment by kanflo** [comment]
@luisbebop, the sysparam is close to be merged. Would you have the time to review this PR?

**Comment by creationix** [comment]
I'm developing a robotics programming environment for kids and designing and implementing my own interpreter that runs on a microcontroller.  I've been looking for a good base and a good cheap chip for my image.  Once this open-rtos version gets native websockets I think it will be perfect!

In other words, I'm excited.  When this is ready to merge, I'll happily test it on any of my various esp8266 hardware boards, I've collected several variants in my research.

**Comment by hugows** [comment]
Hi @luisbebop , any updates on this?

**Comment by luisbebop** [comment]
Hi @hugows 

Unfortunately didn't have time to keep changing and supporting the project.
Feel free to fork my changes and update on the branch master.

**Pull request closed without merging**
