### PR TITLE
Softuart

### PR DESCRIPTION
**Pull request by mr-nice**
This is a port of esp8266-software-uart [1] to esp-open-rtos.

For now only RX is working and it must be configured at the softuart.h file. This can now be easily fixed with the new gpio_inter handlers.

The license is MIT which should be compatible with BSD.

1 https://github.com/plieningerweb/esp8266-software-uart

### CODE REVIEW

**Comment by UncleRus** [comment]
Thank you.
But I think this contribution will be incomplete without the TX part.

**Comment by UncleRus** [comment]
Any news about the TX part, @mr-nice ?

**Comment by Zaltora** [comment]
error at  softuart_init(uint32_t baudrate) with `sdk_os_delay_us(100000);`.
This delay is not necessary, i guess ? . Use vTaskDelay for large delay as discussed at #323 when you need it.
Nice addition @mr-nice  !

**Comment by mr-nice** [comment]
Thanks for your comment I will change this part to use vTaskDelay.
To be honest I did not know that pull requests are tracking the branches. But if you know it it is a nice feature :) The TX part is from lzzbhad  and unfortunately I have no other device to test the TX part. Maybe someone with a second device can test it?

**Comment by Zaltora** [comment]
You can test it with your computer ? just use hardware pin as software pin. I will try to test it this week if i got time.
I dont think this delay is usefull.  I dont found timing specification for UART.  You can remove it or reduce time to 1 ms. ( If no objections )

**Comment by UncleRus** [comment]
@mr-nice Could you please allow maintainers to edit this PR?
[Enabling repository maintainer permissions on existing pull requests](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/#enabling-repository-maintainer-permissions-on-existing-pull-requests)

**Comment by mr-nice** [comment]
I think you are right about the delay. I am not sure why it is there maybe to wait that the GPIO is long enought high after the gpio_write(1) at //Set Tx  to trigger a edge. But the gpio_write should be blocking anyways and I think a shorter delay could work. 

I hope I am able to find some time to test it this week :)

**Comment by mr-nice** [comment]
@UncleRus I clicked the [] Allow edits from maintainers and the checkbox is now OK. Please tell me if it works out for you :)

**Comment by UncleRus** [comment]
@mr-nice Thank you!

**Pull request merged**
