### PR TITLE
C++ Support

### PR DESCRIPTION
**Pull request by projectgus**
This is a PR based on @mikejac's work mentioned in #17, plus tweaks to the Makefile and support for global constructors (currently hacked in just before the FreeRTOS scheduler starts, can be put in a better place once #2 is done.)

I don't usually do C++ on microcontrollers so I'm not sure what else is necessary for this to be useful - new/delete operators? STL support?

### CODE REVIEW

**Comment by mikejac** [comment]
Great :-)

1) Yes to new/delete operators (have them locally - and here: http://pastebin.com/Wj1Cyvt6).
2) Don't think so for STL support. Would be really nice, but that's probably too much for a device like the ESP8266.

**Comment by igrr** [comment]
Some parts of STL work quite well even on cores with much less memory than 8266. In the 8266 arduino core and libraries i use `<algorithm>` for some algorithms, <memory> for `std::shared_ptr`, and <function> for `std::function`, `std::bind` and other goodness. Others have even used `std::vector` without apparent issues.

Apart from things you already have, and new/delete operators mentioned above, you might also need some error-handling functions like `__throw_bad_function_call`, `__throw_length_error`, `__throw_bad_alloc`, `__cxa_deleted_virtual`, `__cxa_pure_virtual` — just make them call `abort` or something equivalent. If you want people to use local static variables with non-zero initializers you will also need `__cxa_guard_acquire`, `__cxa_guard_release`, and `__cxa_guard_abort`.

**Comment by projectgus** [comment]
Thanks @igrr, appreciate the insight as always. :)

I see Arduino compiles with -fno-exceptions as well, same as the support @mikejac contributed. Just curious, is this just for performance & code size reasons or do C++ exceptions break the current gcc call0 ABI support?

**Comment by jcmvbkbc** [comment]
> Just curious, is this just for performance & code size reasons or do C++ exceptions break the current gcc call0 ABI support?

C++ exceptions work in call0 ABI, with the only possible exception (put not intended) of stack unwinding over the signal frame, which must be implemented in OS-specific way anyway.
But they pull a lot from libgcc, so that in my tests empty program that only throws one exception doesn't fit into esp8266 IRAM. It may work if libgcc is relocated to FLASH though.

**Comment by projectgus** [comment]
Interesting, thanks @jcmvbkbc. The esp-open-rtos linker script only puts the [integer support functions (*i3.o) into IRAM](https://github.com/SuperHouse/esp-open-rtos/blob/master/ld/eagle.app.v6.ld#L235), so it's probably OK from the libgcc point of view.

Still might not be a super useful feature in the esp8266 context, but I'll give it a try anyhow.

**Comment by projectgus** [comment]
Realised we could fix the weak linking problem by just being intelligent about library order in the linker arguments. Not sure why I didn't realise that earlier.

If you rebase this pull against current master with 0090153, it will link correctly without any init function tricks because the strong-linked _read_r is seen by the linker first.

However to be honest I'm still not sure about merging this, I think a driver that uses the FIFO buffer registers will probably meet most people's needs (128 byte buffer) and has basically no resource overhead.

**Comment by projectgus** [comment]
(Sorry, commit 0090153 and the follow-up comment were meant for pull #31 not this one. Please ignore.)

**Pull request merged**
