### PR TITLE
sntp: free the pbuf after sending the request

### PR DESCRIPTION
**Pull request by iosen**
Fixes a memory leak.

### CODE REVIEW

**Comment by kanflo** [comment]
Nice catch, thanks!

**Comment by projectgus** [comment]
This looks like a good fix, thanks for contributing it. I think we could bypass the check of bpuf->ref - the pbuf is allocated inside the function so it should always have ref count 1. What do you think?

**Comment by iosen** [comment]
Thanks for the feedback. Removed the 'bpuf->ref'.

**Comment by projectgus** [comment]
Thanks!

**Pull request merged**
