### PR TITLE
sysparam: add a semaphore to synchronize writers.

### PR DESCRIPTION
**Pull request by ourairquality**
This synchronizes writers, but not yet readers.

It appears the code supports multiple readers and a single writer. There seems to be an issue with multiple compaction still to be explored, but this PR is start to at least synchronize the writers.

### CODE REVIEW

**Comment by foogod** [comment]
This seems reasonable to me.  Note that there shouldn't be any need to synchronize readers, since with the atomic update process they are entirely threadsafe, even when there is a writer making updates at the same time, so we should only need to protect against multiple simultaneous writes..

**Comment by ourairquality** [comment]
Looking over the read paths there seem to be more thread safety issues, and I think readers need locking too. For example consider `_find_entry` accessing `_sysparam_info.cur_base` which a writer could change.

I don't buy the argument that other code has more significant issues so this code need not be safe, and I doubt other people do either.

Locking readers might mean that the `sysparam_iter_*` functions need to go, or be some separate reflective debug code and not for production use. Perhaps better to change the API to return a list of the key names, rather than an iterator, or to return a key matching a given index, anything atomic.

**Comment by kanflo** [comment]
Thanks for this fix @ourairquality. I guess you considered one single semaphore for the entire sysparam? I guess it boils down to what usage one sees in sysparam. Personally, I do not regard it as a high traffic data store. Thus, having a global lock would be fine by me. Others may of course have a different view of sysparam and therefore want a more fine grain locking, for performance.

**Comment by ourairquality** [comment]
@kanflo The changes in https://github.com/SuperHouse/esp-open-rtos/pull/195 include better thread safety support also for reads. Perhaps I should have closed this.

**Comment by kanflo** [comment]
Bummer, I was coming to #195. Perhaps those changes could be broken out of that PR?

**Pull request merged**
