### PR TITLE
I2C clock timing improvements - fix of #480

### PR DESCRIPTION
**Pull request by gschorcht**
Suggestion for improving clock timing a lot, at least for 80 MHz system clock and 80 kHz and 100 kHz I2C SCL clock.

### CODE REVIEW

**Comment by gschorcht** [comment]
Clock timing before the modifications for logical 0:
i2c_problem_1

Clock timing before the modifications for logical 1:
i2c_problem_2

Same transfer after the modifications:
i2c_problem_3

**Comment by Zaltora** [comment]
At 160MHz, what are the signals before and after ?

**Comment by gschorcht** [comment]
How can I test it at 160 MHz?

**Comment by Zaltora** [comment]
Put this in your main:
` sdk_system_update_cpu_freq(160);`

**Comment by gschorcht** [comment]
Thanks, I will try tomorrow.

**Comment by gschorcht** [comment]
After tuning the delays for 160 MHz system clock the results are:

for I2C_FREQ_80K:
i2c_problem_160m_80k_new

for I2C_FREQ_100K
i2c_problem_160m_100k_new

I2C_FREQ_400K:
i2c_problem_160m_400k_new

Not perfect but much better than before, e.g. for I2C_FREQ_100K:
i2c_problem_160m_100k_old

**Comment by flannelhead** [comment]
@gschorcht Thank you for your work on this! I incorporated these changes in https://github.com/SuperHouse/esp-open-rtos/pull/503 which was recently merged - hence this PR can be closed.

**Pull request closed without merging**
