### PR TITLE
WiFi credentials

### PR DESCRIPTION
**Pull request by kanflo**
PR for issue https://github.com/SuperHouse/esp-open-rtos/issues/15

### CODE REVIEW

**Comment by projectgus** [comment]
This looks really good, thanks.

The only thing I noticed is that the #warning line in ssid-config.h is commented out. Is that by accident? I think the warning is a good idea.

Cheers,

Angus

**Comment by kanflo** [comment]
Well that was rather sloppy of me, the warning should be there. I'll revisit the PR later this week.

**Comment by kanflo** [comment]
I amended my previous commit, removing the #warning comment from include/ssid_config.h

**Comment by projectgus** [comment]
Thanks again for these, sorry for the slow reply!

Have merged the header fix and the WiFi credentials fix. I'll open a new PR to discuss/merge the UART changes.

**Pull request closed without merging**
