### PR TITLE
SPI3 support ssd1306

### PR DESCRIPTION
**Pull request by Zaltora**
- Add SPI3 protocol for ssd1306.
- replace 'spi_tranfert_8' by new API 'spi_repeat' to send many 0 ;
- 'cs_pin' and 'addr' share same byte in struct because we dont need both in same time.

I don't get ssd1306 to test it. Need feedback.
I will add SH1106 support as soon as possible

### CODE REVIEW

**Comment by Zaltora** [comment]
Hi, i have tested  with my sh1106/SPI4 . Was working. but unfortunately, my screen is dead...
So i will wait to receive new Sh1106 to test it with all protocols and fix what missing if needed.

**Comment by UncleRus** [comment]
@Zaltora Great contrbution, thank you!
I have tested my SSD1306 in SPI3 mode and it works ok.

**Comment by Zaltora** [comment]
I tested I2C with ssd1306. Work fine.  Need test with sh1106 (all protocols) to valid.

**Comment by UncleRus** [comment]
Hi @Zaltora! Is there any news on testing with SH1106?

**Comment by Zaltora** [comment]
I will receive my screen soon! :)

**Comment by Zaltora** [comment]
hum, i doing wrong i guess.  i had rebase this branch  with master, then solves conflict, then update this PR.

**Pull request merged**
